json encoder
MongoEngine/flask-mongoengine pull request #523
Opened 2023-05-13 17:24 UTC by idoshr

Fix issue while try to inherit from MongoEngineJSONEncoder
and for bonus add doc of how add encoder hope it will be helpful

2023-05-29 04:39 UTC, insspb requested changes
@idoshr thank you for interest to this project. 

I reviewed changes, being out of mongo right now. Please fix mentioned errors and I will recheck again.

2023-05-29 04:39 UTC, insspb commented on flask_mongoengine/json.py
> +            return superclass.default(obj)
What? Where it from?

2023-05-29 04:39 UTC, insspb commented on flask_mongoengine/exceptions.py
> +from werkzeug.exceptions import HTTPException
Please revert this exception and all related changes. Leave it to flask.

2023-05-29 04:39 UTC, insspb commented on docs/custom_json_encoder.md
> +By this way you can handel encoding special object
```suggestion
By this way you can handle encoding special object
```

2023-05-29 04:39 UTC, insspb commented on flask_mongoengine/pagination.py
> +    def __init__(self, iterable, page, per_page, max_depth=None):
If you are working with class, please create docstrings with parameters description. For new and old.

2023-05-29 16:02 UTC, idoshr commented
@insspb 
What is your opinion on adding this default encoder
![image](https://github.com/MongoEngine/flask-mongoengine/assets/35264146/bb5b9aef-60e4-4074-9584-64234cf32a3b)

2023-05-31 09:16 UTC, EvanBldy commented
Hi that's cool ! Thanks
Will you do a new release on pypi after that ?

2023-06-16 15:51 UTC, idoshr commented
This pull request spliced to 3 separated PRs
https://github.com/MongoEngine/flask-mongoengine/pull/526
https://github.com/MongoEngine/flask-mongoengine/pull/527
https://github.com/MongoEngine/flask-mongoengine/pull/528

2023-06-16 15:51 UTC, closed without merging